from __future__ import annotations

from vnpy.web.domain.cb_quant.enums import ExpressionType, FactorCategory, FactorType, FunctionCategory
from vnpy.web.domain.cb_quant.models import FactorMeta, FunctionMeta, FunctionParameterMeta


def _factor(
    *,
    id: str,
    factor_name: str,
    factor_key: str,
    category: FactorCategory,
    factor_type: FactorType = FactorType.DEFAULT,
    expression: str | None = None,
    expression_type: ExpressionType = ExpressionType.NUMERIC,
    enabled: bool = True,
    remark: str = "",
    view_style: int = 0,
    view_precision: int = 2,
    view_color: bool = False,
    view_ratio: float = 1,
    view_unit: str = "",
) -> FactorMeta:
    return FactorMeta(
        id=id,
        factor_name=factor_name,
        factor_key=factor_key,
        category=category,
        factor_type=factor_type,
        expression=expression or f"[{factor_key}]",
        expression_type=expression_type,
        enabled=enabled,
        remark=remark,
        view_style=view_style,
        view_precision=view_precision,
        view_color=view_color,
        view_ratio=view_ratio,
        view_unit=view_unit,
    )


def _param(name: str, type_name: str, type_value: str, description: str = "") -> FunctionParameterMeta:
    return FunctionParameterMeta(
        name=name,
        description=description or f"{name}参数",
        type_name=type_name,
        type=type_value,
    )


def _func(
    category: FunctionCategory,
    name: str,
    formular: str,
    description: str,
    parameters: list[FunctionParameterMeta] | None = None,
) -> FunctionMeta:
    return FunctionMeta(
        category=category,
        name=name,
        formular=formular,
        description=description,
        parameters=parameters or [],
    )


FACTOR_REGISTRY: dict[FactorCategory, tuple[FactorMeta, ...]] = {
    FactorCategory.BASE: (
        _factor(id="01951cab-d544-44c1-a0a0-0323a0200a4f", factor_name="双低", factor_key="dblow", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d544-4c1d-a0e4-ae0086b46bda", factor_name="转股溢价率", factor_key="conv_prem", category=FactorCategory.BASE, view_style=1),
        _factor(id="01951cab-d544-4213-b2cd-81cc911935d1", factor_name="纯债溢价率", factor_key="bond_prem", category=FactorCategory.BASE, view_style=1),
        _factor(id="01951cab-d545-4a7c-ae3d-499569cc70d6", factor_name="理论偏离度", factor_key="theory_bias", category=FactorCategory.BASE, view_style=1),
        _factor(id="01951cab-d545-44e7-bc2c-542b543ca0c5", factor_name="理论价值", factor_key="theory_value", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d545-44dc-8550-5394b911f5b9", factor_name="期权价值", factor_key="option_value", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d544-4ea1-a503-8f31730eaf73", factor_name="纯债价值", factor_key="pure_value", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d545-46df-838c-21b552d582dd", factor_name="转股价值", factor_key="conv_value", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d545-433c-8fbd-9a1fecf8f670", factor_name="转股价格", factor_key="conv_price", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d544-45da-a15c-ea63ff1b4463", factor_name="收盘价", factor_key="close", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d545-498b-9ae9-b5e4f8cba0b2", factor_name="开盘价", factor_key="open", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d545-40f5-b46a-aa3d4f5907a6", factor_name="最高价", factor_key="high", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d545-41b6-8b59-1c85ac4aa350", factor_name="最低价", factor_key="low", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d544-46a2-b9e8-75fc5523aa8e", factor_name="前收盘价", factor_key="pre_close", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d545-44b5-bbb0-780b70b7b554", factor_name="涨跌幅", factor_key="pct_chg", category=FactorCategory.BASE, view_style=1, view_color=True),
        _factor(id="01951cab-d545-4961-b489-a3b05e412b3b", factor_name="成交量(手)", factor_key="vol", category=FactorCategory.BASE, view_precision=1),
        _factor(id="01951cab-d545-413c-a2b2-a1d51fc81186", factor_name="成交额(万)", factor_key="amount", category=FactorCategory.BASE, view_precision=2),
        _factor(id="01951cab-d545-4582-b538-09b2fa2eb35f", factor_name="换手率", factor_key="turnover", category=FactorCategory.BASE, view_style=1),
        _factor(id="01951cab-d545-49ad-ae99-08b153ac2620", factor_name="转债市占比", factor_key="cap_mv_rate", category=FactorCategory.BASE, view_style=1),
        _factor(id="01951cab-d545-4d96-a361-e50a942997a4", factor_name="到期收益率", factor_key="ytm", category=FactorCategory.BASE, view_style=1, view_color=True),
        _factor(id="01951cab-d544-4771-8e2c-a1dee60fb373", factor_name="理论溢价率", factor_key="theory_conv_prem", category=FactorCategory.BASE, view_style=1),
        _factor(id="01951cab-d544-4e5d-b4aa-24c2c6666b6f", factor_name="修正溢价率", factor_key="mod_conv_prem", category=FactorCategory.BASE, view_style=1),
        _factor(id="01951cab-d545-480c-a4db-96f69119e694", factor_name="剩余年限", factor_key="left_years", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d544-455d-a848-24f04f07f821", factor_name="剩余规模(亿)", factor_key="remain_size", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d544-4848-925b-d01845d50477", factor_name="发行规模(亿)", factor_key="issue_size", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d544-4d8b-929d-b398c3e83257", factor_name="剩余市值(亿)", factor_key="remain_cap", category=FactorCategory.BASE, view_precision=3),
        _factor(id="01951cab-d545-42c8-ac69-25cfd2de2d81", factor_name="上市天数", factor_key="list_days", category=FactorCategory.BASE, view_precision=0),
        _factor(id="7cf56c2d-9664-4fc1-a0f3-3a6000f9ccf0", factor_name="涨跌停标记", factor_key="limit", category=FactorCategory.BASE, view_precision=0),
        _factor(id="01951cab-d545-4a1e-bd60-90eb571ef8e4", factor_name="强赎剩余计数", factor_key="redeem_remain_days", category=FactorCategory.BASE, factor_type=FactorType.ADVANCED, enabled=False, view_precision=0),
        _factor(id="01951cab-d545-4ba8-b069-3d37ac355360", factor_name="强赎触发价比率", factor_key="redeem_price_rate", category=FactorCategory.BASE, factor_type=FactorType.ADVANCED, enabled=False, view_style=1, view_precision=0),
        _factor(id="068f2557-8b21-72ee-8000-b5414fc3a35e", factor_name="地域", factor_key="area", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="068f2555-8c36-7751-8000-1fa592c68b82", factor_name="企业类型", factor_key="orgform", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="068f2559-48db-710d-8000-6f09a916c889", factor_name="外部评级", factor_key="rating", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="068f255a-ce11-7133-8000-d80e2589ebee", factor_name="三方评级", factor_key="yy_rating", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="068f255c-d061-76d5-8000-0fbec7cd2b51", factor_name="一级行业", factor_key="industry_1", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="068f255e-215f-7fc3-8000-1520d5d46377", factor_name="二级行业", factor_key="industry_2", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="068f255f-3d89-7b94-8000-f0c24497355b", factor_name="三级行业", factor_key="industry_3", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="068f25ce-79a0-7f4b-8000-e836525fea42", factor_name="强赎状态", factor_key="is_call", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="068f2577-922f-7032-8000-dc381b8e6d67", factor_name="交易日", factor_key="trade_date", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=7, view_precision=0),
        _factor(id="068fa1f4-6231-7db3-8000-1d4dc07f7719", factor_name="转债名称", factor_key="name", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="068f2574-14d3-7b61-8000-c77c9886058a", factor_name="转债代码", factor_key="code", category=FactorCategory.BASE, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
    ),
    FactorCategory.HISTORY: (
        _factor(id="01951cab-d545-4bc6-8eb9-ce6302f99ac6", factor_name="5日乖离率", factor_key="bias_5", category=FactorCategory.HISTORY, factor_type=FactorType.DERIVED, view_style=0),
        _factor(id="01951cab-d545-4be0-bd68-6cc05b2957dd", factor_name="5日涨跌幅", factor_key="pct_chg_5", category=FactorCategory.HISTORY, view_style=1, view_color=True),
        _factor(id="01951cab-d545-4591-b198-9466064a7bb8", factor_name="年化波动率", factor_key="volatility", category=FactorCategory.HISTORY, view_style=1),
        _factor(id="01951cab-d545-44dc-8550-5394b911f5b9", factor_name="5日成交量", factor_key="vol_5", category=FactorCategory.HISTORY, factor_type=FactorType.DERIVED, view_precision=1),
        _factor(id="01951cab-d545-4b70-ab60-7cdfb4a02240", factor_name="5日超额涨跌幅", factor_key="alpha_pct_chg_5", category=FactorCategory.HISTORY, factor_type=FactorType.DERIVED, view_style=1, view_color=True),
        _factor(id="01951cab-d545-4bcd-b765-bbd6c70024d2", factor_name="5日换手率", factor_key="turnover_5", category=FactorCategory.HISTORY, factor_type=FactorType.DERIVED, view_style=1),
        _factor(id="0194fad4-c697-4f63-a2b9-ffa7955bcf47", factor_name="5日成交额", factor_key="amount_5", category=FactorCategory.HISTORY, factor_type=FactorType.DERIVED, view_precision=2),
        _factor(id="01951cab-d545-4513-a129-bb861fc07aa5", factor_name="5日均价", factor_key="close_ma_5", category=FactorCategory.HISTORY, factor_type=FactorType.DERIVED, view_precision=3),
        _factor(id="01951cab-d545-4572-ada7-b8e0794039e2", factor_name="正股5日涨跌幅", factor_key="pct_chg_5_stk", category=FactorCategory.HISTORY, view_style=1, view_color=True),
        _factor(id="01951cab-d545-4ec4-981b-86488b736e2f", factor_name="正股年化波动率", factor_key="volatility_stk", category=FactorCategory.HISTORY, view_style=1),
    ),
    FactorCategory.STOCK: (
        _factor(id="01951cab-d545-4045-b059-e219867bfe89", factor_name="正股涨跌幅", factor_key="pct_chg_stk", category=FactorCategory.STOCK, view_style=1, view_color=True),
        _factor(id="01951cab-d545-4a47-a34f-6a21496e4fda", factor_name="正股收盘价", factor_key="close_stk", category=FactorCategory.STOCK, expression_type=ExpressionType.TEXT, view_style=3),
        _factor(id="068f4370-6034-7e6d-8000-c3d01d8ac4a4", factor_name="正股开盘价", factor_key="open_stk", category=FactorCategory.STOCK, expression_type=ExpressionType.TEXT, view_style=3),
        _factor(id="068f4372-248f-7d46-8000-81036c51a70e", factor_name="正股最高价", factor_key="high_stk", category=FactorCategory.STOCK, expression_type=ExpressionType.TEXT, view_style=3),
        _factor(id="068f4373-8789-7cc0-8000-02beff8c57d5", factor_name="正股最低价", factor_key="low_stk", category=FactorCategory.STOCK, expression_type=ExpressionType.TEXT, view_style=3),
        _factor(id="068f45dd-e983-72bd-8000-1b302b96206b", factor_name="正股代码", factor_key="code_stk", category=FactorCategory.STOCK, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="068f45eb-ae6b-767c-8000-a772079f907c", factor_name="正股名称", factor_key="name_stk", category=FactorCategory.STOCK, expression_type=ExpressionType.TEXT, view_style=6, view_precision=0),
        _factor(id="01951cab-d545-40f9-82e4-22da1468a6c2", factor_name="正股流通市值(亿)", factor_key="circ_mv", category=FactorCategory.STOCK, view_precision=3),
        _factor(id="01951cab-d545-431b-abf6-84ad350397eb", factor_name="正股总市值(亿)", factor_key="total_mv", category=FactorCategory.STOCK, view_precision=3),
        _factor(id="01951cab-d545-46db-bf9f-312d6ec05640", factor_name="正股成交额(万)", factor_key="amount_stk", category=FactorCategory.STOCK, view_precision=2),
        _factor(id="01951cab-d545-4906-afd8-e97a5e9ece30", factor_name="正股成交量", factor_key="vol_stk", category=FactorCategory.STOCK, view_precision=2),
        _factor(id="01951cab-d545-43a5-9994-9aec86114244", factor_name="市盈率TTM", factor_key="pe_ttm", category=FactorCategory.STOCK, view_precision=2),
        _factor(id="01951cab-d545-4869-bfd1-9e4857c2e0d0", factor_name="市销率TTM", factor_key="ps_ttm", category=FactorCategory.STOCK, view_precision=2),
        _factor(id="01951cab-d545-4d64-8a12-9cd7bbfc7f7a", factor_name="市净率", factor_key="pb", category=FactorCategory.STOCK, view_precision=2),
        _factor(id="01951cab-d545-49b6-afd5-ee97c60b4c45", factor_name="股息率", factor_key="dv_ratio", category=FactorCategory.STOCK, view_style=1),
        _factor(id="01951cab-d545-484d-850c-9a0966f0e13a", factor_name="资产负债率", factor_key="debt_to_assets", category=FactorCategory.STOCK, view_style=1),
    ),
}


FUNCTION_REGISTRY: dict[FunctionCategory, tuple[FunctionMeta, ...]] = {
    FunctionCategory.CROSS_SECTION: (
        _func(FunctionCategory.CROSS_SECTION, "cs_cor", "cs_cor(指标1: 数值向量, 指标2: 数值向量)", "返回每交易日两个指标的当日协方差", [_param("指标1", "数值向量", "number_vector"), _param("指标2", "数值向量", "number_vector")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_corr", "cs_corr(指标1: 数值向量, 指标2: 数值向量)", "返回每交易日两个指标的当日相关度", [_param("指标1", "数值向量", "number_vector"), _param("指标2", "数值向量", "number_vector")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_count", "cs_count()", "统计交易日截面（不含停牌标的）的标的个数。"),
        _func(FunctionCategory.CROSS_SECTION, "cs_quantile", "cs_quantile(指标: 数值向量, 分位数: 数值)", "计算交易日截面指标的分位数。", [_param("指标", "数值向量", "number_vector"), _param("分位数", "数值", "number")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_rank", "cs_rank(指标: 数值向量, 排序标记: 布尔值)", "计算交易日截面指标排名。", [_param("指标", "数值向量", "number_vector"), _param("排序标记", "布尔值", "boolean")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_pct_rank", "cs_pct_rank(指标: 数值向量)", "计算交易日截面指标的百分位排名。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_mean", "cs_mean(指标: 数值向量)", "计算交易日截面指标均值。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_max", "cs_max(指标: 数值向量)", "计算交易日截面指标最大值。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_min", "cs_min(指标: 数值向量)", "计算交易日截面指标最小值。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_median", "cs_median(指标: 数值向量)", "计算交易日截面指标中位数。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_std", "cs_std(指标: 数值向量)", "计算交易日截面指标标准差。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_var", "cs_var(指标: 数值向量)", "计算交易日截面指标方差。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.CROSS_SECTION, "cs_sum", "cs_sum(指标: 数值向量)", "计算交易日截面指标求和。", [_param("指标", "数值向量", "number_vector")]),
    ),
    FunctionCategory.TIME_SERIES: (
        _func(FunctionCategory.TIME_SERIES, "ts_arg_max", "ts_arg_max(指标: 数值向量, 交易日: 数值)", "返回窗口内最大值的索引值。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_arg_min", "ts_arg_min(指标: 数值向量, 交易日: 数值)", "返回窗口内最小值的索引值。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_cor", "ts_cor(指标1: 数值向量, 指标2: 数值向量, 交易日: 数值)", "计算时间序列协方差。", [_param("指标1", "数值向量", "number_vector"), _param("指标2", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_corr", "ts_corr(指标1: 数值向量, 指标2: 数值向量, 交易日: 数值)", "计算时间序列相关系数。", [_param("指标1", "数值向量", "number_vector"), _param("指标2", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_ema", "ts_ema(指标: 数值向量, 交易日: 数值)", "指数移动平均。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_shift", "ts_shift(指标: 数值向量, 交易日: 数值)", "获取指标几个交易日前的值。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_max", "ts_max(指标: 数值向量, 交易日: 数值)", "计算窗口内最大值。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_min", "ts_min(指标: 数值向量, 交易日: 数值)", "计算窗口内最小值。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_mean", "ts_mean(指标: 数值向量, 交易日: 数值)", "计算窗口内均值。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_median", "ts_median(指标: 数值向量, 交易日: 数值)", "计算窗口内中位数。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_quantile", "ts_quantile(指标: 数值向量, 交易日: 数值, 分位数: 数值)", "计算窗口内分位数值。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number"), _param("分位数", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_std", "ts_std(指标: 数值向量, 交易日: 数值)", "计算窗口内标准差。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_var", "ts_var(指标: 数值向量, 交易日: 数值)", "计算窗口内方差。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_sum", "ts_sum(指标: 数值向量, 交易日: 数值)", "计算窗口内求和。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_rank", "ts_rank(指标: 数值向量, 交易日: 数值)", "计算窗口内排名。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_skew", "ts_skew(指标: 数值向量, 交易日: 数值)", "计算窗口内偏度。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_kurtosis", "ts_kurtosis(指标: 数值向量, 交易日: 数值)", "计算窗口内峰度。", [_param("指标", "数值向量", "number_vector"), _param("交易日", "数值", "number")]),
        _func(FunctionCategory.TIME_SERIES, "ts_lin_reg", "ts_lin_reg(指标x: 数值向量, 指标y: 数值向量, 交易日: 数值, 返回类型: 文本)", "计算线性回归拟合值、斜率、截距、r2、残差。", [_param("指标x", "数值向量", "number_vector"), _param("指标y", "数值向量", "number_vector"), _param("交易日", "数值", "number"), _param("返回类型", "文本", "string")]),
    ),
    FunctionCategory.MATH: (
        _func(FunctionCategory.MATH, "abs", "abs(指标: 数值向量)", "绝对值。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "sign", "sign(指标: 数值向量)", "正负符号。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "round", "round(指标: 数值向量, 小数位数: 数值)", "四舍五入。", [_param("指标", "数值向量", "number_vector"), _param("小数位数", "数值", "number")]),
        _func(FunctionCategory.MATH, "ceil", "ceil(指标: 数值向量)", "向上取整。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "floor", "floor(指标: 数值向量)", "向下取整。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "sqrt", "sqrt(指标: 数值向量)", "平方根。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "cbrt", "cbrt(指标: 数值向量)", "立方根。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "exp", "exp(指标: 数值向量)", "自然指数。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "log", "log(指标: 数值向量)", "自然对数。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "sin", "sin(指标: 数值向量)", "正弦。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "cos", "cos(指标: 数值向量)", "余弦。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "tan", "tan(指标: 数值向量)", "正切。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "sinh", "sinh(指标: 数值向量)", "双曲正弦。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "cosh", "cosh(指标: 数值向量)", "双曲余弦。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "tanh", "tanh(指标: 数值向量)", "双曲正切。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "arccos", "arccos(指标: 数值向量)", "反余弦。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "arctan", "arctan(指标: 数值向量)", "反正切。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "arcsinh", "arcsinh(指标: 数值向量)", "反双曲正弦。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "arctanh", "arctanh(指标: 数值向量)", "反双曲正切。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "cot", "cot(指标: 数值向量)", "余切。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "degrees", "degrees(指标: 数值向量)", "转换为角度。", [_param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.MATH, "radians", "radians(指标: 数值向量)", "转换为弧度。", [_param("指标", "数值向量", "number_vector")]),
    ),
    FunctionCategory.OTHER: (
        _func(FunctionCategory.OTHER, "when", "when(条件: 数值向量, 指标1: 数值向量, 指标2: 数值向量)", "根据条件返回不同值。", [_param("条件", "数值向量", "number_vector"), _param("指标1", "数值向量", "number_vector"), _param("指标2", "数值向量", "number_vector")]),
        _func(FunctionCategory.OTHER, "contains", "contains(字符串列: 文本向量, 子串: 文本)", "判断是否包含指定子串（支持正则）。", [_param("字符串列", "文本向量", "string_vector"), _param("子串", "文本", "string")]),
        _func(FunctionCategory.OTHER, "start_with", "start_with(字符串列: 文本向量, 前缀: 文本)", "判断是否以前缀开头。", [_param("字符串列", "文本向量", "string_vector"), _param("前缀", "文本", "string")]),
        _func(FunctionCategory.OTHER, "end_with", "end_with(字符串列: 文本向量, 后缀: 文本)", "判断是否以后缀结尾。", [_param("字符串列", "文本向量", "string_vector"), _param("后缀", "文本", "string")]),
    ),
    FunctionCategory.TECHNICAL: (
        _func(FunctionCategory.TECHNICAL, "MA多头", "MA多头(快线周期: 数值, 慢线周期: 数值, 指标: 数值向量)", "MA快线在慢线上方。", [_param("快线周期", "数值", "number"), _param("慢线周期", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "MA空头", "MA空头(快线周期: 数值, 慢线周期: 数值, 指标: 数值向量)", "MA快线在慢线下方。", [_param("快线周期", "数值", "number"), _param("慢线周期", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "EMA_多头", "EMA_多头(短期: 数值, 长期: 数值, 指标: 数值向量)", "短期EMA在长期EMA上方返回1。", [_param("短期", "数值", "number"), _param("长期", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "EMA_空头", "EMA_空头(短期: 数值, 长期: 数值, 指标: 数值向量)", "短期EMA在长期EMA下方返回1。", [_param("短期", "数值", "number"), _param("长期", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "量比", "量比(N: 数值, M: 数值)", "量比 = N日平均成交量 / M日平均成交量", [_param("N", "数值", "number"), _param("M", "数值", "number")]),
        _func(FunctionCategory.TECHNICAL, "乖离率", "乖离率(周期: 数值, 指标: 数值向量)", "乖离率 = (指标值 - N日均线) / N日均线。", [_param("周期", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "布林中轨", "布林中轨(周期: 数值, 指标: 数值向量)", "中轨 = N日移动平均线。", [_param("周期", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "布林上轨", "布林上轨(周期: 数值, 标准差倍数: 数值, 指标: 数值向量)", "上轨 = 中轨 + k * 标准差。", [_param("周期", "数值", "number"), _param("标准差倍数", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "布林下轨", "布林下轨(周期: 数值, 标准差倍数: 数值, 指标: 数值向量)", "下轨 = 中轨 - k * 标准差。", [_param("周期", "数值", "number"), _param("标准差倍数", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "布林带宽", "布林带宽(周期: 数值, 标准差倍数: 数值, 指标: 数值向量)", "带宽 = (上轨 - 下轨) / 中轨。", [_param("周期", "数值", "number"), _param("标准差倍数", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "布林突破上轨", "布林突破上轨(周期: 数值, 标准差倍数: 数值, 指标: 数值向量)", "价格突破上轨时返回1。", [_param("周期", "数值", "number"), _param("标准差倍数", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "布林突破下轨", "布林突破下轨(周期: 数值, 标准差倍数: 数值, 指标: 数值向量)", "价格突破下轨时返回1。", [_param("周期", "数值", "number"), _param("标准差倍数", "数值", "number"), _param("指标", "数值向量", "number_vector")]),
        _func(FunctionCategory.TECHNICAL, "波动率", "波动率(指标: 数值向量, 周期: 数值)", "波动率 = N日收益率标准差 * sqrt(N)。", [_param("指标", "数值向量", "number_vector"), _param("周期", "数值", "number")]),
        _func(FunctionCategory.TECHNICAL, "trend_score", "trend_score(指标: 数值向量, 回归窗口: 数值, 年均交易日数: 数值)", "趋势得分。", [_param("指标", "数值向量", "number_vector"), _param("回归窗口", "数值", "number"), _param("年均交易日数", "数值", "number")]),
        _func(FunctionCategory.TECHNICAL, "RSRS", "RSRS(指标x: 数值向量, 指标y: 数值向量, 回归窗口: 数值, 标准化窗口: 数值, 返回类型: 文本)", "RSRS 指标（zscore / zscore_r2 / zscore_right）。", [_param("指标x", "数值向量", "number_vector"), _param("指标y", "数值向量", "number_vector"), _param("回归窗口", "数值", "number"), _param("标准化窗口", "数值", "number"), _param("返回类型", "文本", "string")]),
    ),
    FunctionCategory.LOGIC: (
        _func(FunctionCategory.LOGIC, "not_", "not_(条件: 布尔值向量)", "逻辑非。", [_param("条件", "布尔值向量", "boolean_vector")]),
        _func(FunctionCategory.LOGIC, "or_", "or_(条件1: 布尔值向量, 条件2: 布尔值向量)", "逻辑或。", [_param("条件1", "布尔值向量", "boolean_vector"), _param("条件2", "布尔值向量", "boolean_vector")]),
        _func(FunctionCategory.LOGIC, "and_", "and_(条件1: 布尔值向量, 条件2: 布尔值向量)", "逻辑与。", [_param("条件1", "布尔值向量", "boolean_vector"), _param("条件2", "布尔值向量", "boolean_vector")]),
    ),
    FunctionCategory.CALENDAR: (
        _func(FunctionCategory.CALENDAR, "day_of_week", "day_of_week(date_expr: 日期向量 | 日期)", "计算星期几（1=周一，7=周日）。", [_param("date_expr", "日期向量|日期", "date_vector|date")]),
        _func(FunctionCategory.CALENDAR, "day_of_year", "day_of_year(date_expr: 日期向量 | 日期)", "计算一年中的第几天。", [_param("date_expr", "日期向量|日期", "date_vector|date")]),
        _func(FunctionCategory.CALENDAR, "day_of_month", "day_of_month(date_expr: 日期向量 | 日期)", "计算一月中的第几天。", [_param("date_expr", "日期向量|日期", "date_vector|date")]),
        _func(FunctionCategory.CALENDAR, "month_of_year", "month_of_year(date_expr: 日期向量 | 日期)", "计算一年中的第几月。", [_param("date_expr", "日期向量|日期", "date_vector|date")]),
        _func(FunctionCategory.CALENDAR, "quarter", "quarter(date_expr: 日期 | 日期向量)", "计算季度（1-4）。", [_param("date_expr", "日期|日期向量", "date|date_vector")]),
        _func(FunctionCategory.CALENDAR, "year", "year(date_expr: 日期 | 日期向量)", "计算年份。", [_param("date_expr", "日期|日期向量", "date|date_vector")]),
    ),
}

