DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tenx') THEN
    CREATE ROLE tenx LOGIN PASSWORD 'tenx';
  ELSE
    ALTER ROLE tenx WITH LOGIN PASSWORD 'tenx';
  END IF;
END
$$;

SELECT 'CREATE DATABASE tenx OWNER tenx'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'tenx')\gexec

GRANT ALL PRIVILEGES ON DATABASE tenx TO tenx;
